### ISSUE TITLE
Allow all socket types to send multipart messages

### ISSUE THREAD

**Issue by nhuff** [zeromq/zmq.rs#119]
As far as I can see from the current code REQ/REP and PUB/SUB sockets can't send multipart messages.  That seems to be inconsistent with the spec.  I have made some changes [here](https://github.com/nhuff/zmq.rs/tree/multipart) to support sending multipart messages on all sockets.  The change is fairly intrusive since it changes the ZmqMessage struct to be a wrapper around a VecDeque<Bytes> instead of just a Bytes field.  It also changes all the send/recv methods to take and return ZmqMessage structs.  I figured it might be worth discussion before I opened a really big pull request.

**Comment by Alexei-Kornienko** [comment]
I think it's not the best approach to fix this. IMHO it might be better to use enum Message instead - https://github.com/zeromq/zmq.rs/blob/master/src/codec/mod.rs#L24

We could possibly allow user to send and recv it and it can be either a single message or a multipart messages.
To support this we need to provide a number of From impl. to make it easier for end users to convert their data to Message.
One of the issues I see in your commit is that you make examples a bit more complicated and it mean that user will have to write more code for a trivial use case.

**Comment by Alexei-Kornienko** [comment]
I think optimal solution would be to:
1) Expose Message enum in public interface and use it as a parameter for send/recv
2) Implement number of From<...> for Message enum and construct a basic message with them (this means that trivial usecase would still be simple and won't require much code)
3) For a more complex cases end user would be able to construct this enum and pass multipart messages when needed

**Comment by TheButlah** [comment]
Yeah having users push into messages is a little too verbose imo. I'd rather accept an IntoIterator of ZmqMessage or something

**Comment by Alexei-Kornienko** [comment]
I can try to implement a draft patch in the next few days to show you my idea of how it can be done.

**Comment by TheButlah** [comment]
Ok, although since the design space for this is large, might be better to post your idea of the signatures so we can discuss and iterate on the design

**Comment by nhuff** [comment]
There are definitely ergonomic improvements that should be made.  Implementing parse() and to_string() for ZmqMessage would go a long way to making the simple case simpler. The things I like about what I implemented are

1. You can handle all messages with send/recv.  You don't need send_mulitpart/recv_multipart.
2. It removes the special case of the single frame message internally. It is just a message no matter how many frames it has.
3. It matches the semantics of how messages are used in zmq.  Many sockets and intermediaries work by adding and removing headers from the front of a message which maps easily to push_front()/pop_front()

**Comment by Alexei-Kornienko** [comment]
>to_string() for ZmqMessage would go a long way to making the simple case simpler.
You cannot implement to_string cause ZmqMessage is not guaranteed to be a valid UTF8 string. There is already try_into() that can convert message to string but it can also return an error in case of invalid unicode

>You can handle all messages with send/recv. You don't need send_mulitpart/recv_multipart.

valid point

>It matches the semantics of how messages are used in zmq. Many sockets and intermediaries work by adding and removing headers from the front of a message which maps easily to push_front()/pop_front()

I agree that it might be usefull. However I hope that we can implement it without additional costs of making it more complex for users.

In any case you can surely open a MR from your fork and we can compare different approaches and pick the best one

**Comment by Alexei-Kornienko** [comment]
Made a draft MR to show my idea ^. @nhuff idea regarding VecDeque might also be adopted cause it would simplify code in couple of places.
Please note that I've added a bunch of helpers to cast between various types and Message enum. Maybe we should have more of thoose

**Comment by nhuff** [comment]
Let me try adding some ergonomic improvements to what I have and I will submit a Draft PR to look at.

**Comment by TheButlah** [comment]
As a heads up, not all zmq socket types support multipart messages. For example, [Client-Server](https://rfc.zeromq.org/spec/41/#overall-goals-of-this-pattern) and [Radio-Dish](https://rfc.zeromq.org/spec/48/#overall-goals-of-this-pattern). When we add support for multipart messages, we will not be able to add it for all socket types.

**Comment by Alexei-Kornienko** [comment]
@TheButlah I like the idea of having only 1 send/recv pair (cause it also allows us to implement Stream/Sink for sockets).
IMHO certain socket type can just return an error if user tries to send multipart messages trough it.

Also please note that RFCs you mentioned are still in draft state so there is no guarantee that they won't be changed or completely dropped.

However I still think that we need to distinguish between single message and multipart message. MR that I proposed leverages the idea that by default aka simple case user can easily cast their type to a single message (or can easily implement his own From trait) something like:
```
From<ZmqMessage> for UserCustomType
```
So I think that it might be convenient to expose some Message/Multipart type to user.

>As an aside, is there any point to the blocking variants of the traits since everything ought to be async?

Certain sockets are not supposed to be async. Pub socket for example (https://github.com/zeromq/zmq.rs/blob/master/src/pub.rs#L158) Doesn't use any await in it. Cause it's not allowed to `block` (wait) by the spec. That's why originally I though that it might be usefull to have Blocking/NonBlocking Send/Recv so different socket types can impl different traits to make their behaviour more transparent

**Comment by TheButlah** [comment]
> Certain sockets are not supposed to be async. Pub socket for example (https://github.com/zeromq/zmq.rs/blob/master/src/pub.rs#L158) Doesn't use any await in it

Slightly confused - that line is marked as async. It looks like nothing actually implements NonBlockingSend. I think I understand what you mean though - you mean that for example pub sockets should return immediately whereas req sockets should block.

I would argue that since we are using an asynchronous executor anyway, and that the function signatures are the same in both cases except one has the async keyword and the other doesn't, that we should consider just having one version of the trait to keep the api simple. And I'd the code eventually evolves to where we need to call some async code inside that function (for example, to push to a async channel), we would need the async keyword anyway. I'll open a separate issue for this to avoid bogging down this one on a tangent.

**Comment by nhuff** [comment]
I added a Draft PR that has implementations for converting from a string to a single frame message and try_from to go from a single frame message to a String.  I also updated the examples to use that functionality.  The examples end up being almost unchanged.
